# Numpy - 그 밖의 형태

## #01. 준비과정

### [1] 패키지 참조

In [2]:
import numpy as np


## #02. 2차원 배열
### [1] 2차원 배열의 생성

In [3]:
# 철수의 학년-과목별 점수
grade = np.array([
    [98,72,80,64],
    [88,90,80,72],
    [92,88,82,76]
])
grade

array([[98, 72, 80, 64],
       [88, 90, 80, 72],
       [92, 88, 82, 76]])

### [2] 2차원 배열의 크기
#### (1) 차원 크기

In [4]:
grade.ndim

2

#### (2) 각 차원별 원소수

In [5]:
grade.shape

(3, 4)

#### (3) 원소의 데이터 타입

In [6]:
grade.dtype

dtype('int32')

### [3] 2차원 배열의 기초 통계량

#### [1] 각 열끼리 덧셈

In [7]:
s1 = np.sum(grade)
print(type(s1))
print(s1)



<class 'numpy.int32'>
982


In [8]:
s2 = np.sum(grade,axis =0)
print(type(s2))
print(s2)



<class 'numpy.ndarray'>
[278 250 242 212]


#### [2] 각 행끼리 덧셈

In [9]:
s3 = np.sum(grade,axis =1)
print(type(s3))
print(s3)

<class 'numpy.ndarray'>
[314 330 338]


### [4] 조건검색
#### (1) boolean 타입으로 인덱싱

In [10]:
bool_array = np.array([
    [True, False, True, False],
    [True, True, True, False],
    [True, True, True, False]
])

# 조건에 맞는 항목만 1차 배열로 추출
result1 = grade[bool_array]
result1 

array([98, 80, 88, 90, 80, 92, 88, 82])

#### (2) 비교식에 의한 검색

80점 이상인지 판별하여 조건에 맞는 데이터만 추려냄

In [11]:
result2 = grade[grade >= 80]
result2
result3 = grade[np.logical_and(grade >= 80, grade <=90)]
result3
result4 = grade[np.logical_or(grade < 80, grade >90)]
result4

array([98, 72, 64, 72, 92, 76])

## 03. 정형화된 배열 생성

### [1] 모든 원소가 `0`인 배열(영배열)


In [12]:
np.zeros([3, 4]) # 파라미터로 리스트나 튜플로 줘야함 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### [2] 모든원소가 1인 배열

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### [3] 모든 원소가 특정값인 배열

In [14]:
np.full((3,4),10) # np.ones([3,4])*10  차이는 정수를 입력했을 때 int타입이냐 float타입이냐의 차이가 있음 ones는 float타입


array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

### [4] 단위행렬 ( diagonal matrix )
대각선으로 `1`이고 나머지 원소는 모두 `0`인 배열

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## #04. 랜덤배열

### [1] `0`부터 `1`의 범위에서 균등하게 추출하여 N차원 배열 생성

#### 10개의 값을 갖는 1차원 배열

In [17]:
np.random.rand(10)

array([0.06597219, 0.44857027, 0.13945134, 0.37024903, 0.32662076,
       0.70715663, 0.51699113, 0.01862198, 0.52148272, 0.31740515])

#### 4행, 3열인 2차원 배열

In [18]:
np.random.rand(4, 3)

array([[0.57216136, 0.19348204, 0.27273685],
       [0.28894684, 0.95567581, 0.18050863],
       [0.52818805, 0.74292031, 0.29064385],
       [0.25566211, 0.24245704, 0.74485897]])

### [2] 주어진 범위 안에서 정수값을 갖는 랜덤 배열

#### `0`부터 `9`사이의 랜덤값 10개의 원소를 갖는 1차원 배열

In [19]:
np.random.randint(0,9,10)

array([0, 2, 8, 3, 2, 4, 0, 1, 8, 5])

#### `0`부터 `9`사이의 랜덤값 10개의 원소를 갖는 3행 4열의 2차원 배열

In [20]:
np.random.randint(0,9,(3,4)) # 리스트나 튜플로 행열의 갯수를 준다

array([[8, 6, 4, 2],
       [4, 6, 1, 0],
       [4, 7, 7, 7]])

### [3] 표준 정규 분포를 따르는 랜덤 배열
#### 1차원 배열

In [29]:
np.random.randn(10)

array([-1.40197328, -0.1009182 , -0.54824245, -0.14461951,  0.35402033,
       -0.03551303,  0.56573831,  1.5456588 , -0.97423633, -0.07034488])

#### 2차원 배열

In [22]:
np.random.randn(4,3)

array([[-3.88065737e-01,  2.55163757e-01, -2.96878177e-01],
       [ 5.77762925e-01,  7.04544569e-04, -6.48412645e-01],
       [-1.06505773e-01, -4.04403002e-01,  1.43400983e-01],
       [-8.89327676e-01,  1.60921188e+00,  1.76738005e+00]])

### [4] 정규분포를 직접 설정

#### 1차원

평균은 `0`, 표준편차 `1`인 정규 분포에서 10개의 수를 추출

In [23]:

np.random.normal(0,1,10)

array([ 1.52116035, -1.76689505,  2.4779746 , -0.7719296 , -1.19761916,
        1.44697297, -1.79778533,  0.95560422, -0.07407094,  1.29014684])


#### 2차원

In [24]:
np.random.normal(0,1,(4,3))

array([[-1.35063862, -1.47354378,  0.06994571],
       [ 1.8381496 , -1.14453364,  0.56494335],
       [ 0.32477196,  0.40239298,  0.07127953],
       [ 0.12612254, -0.52942864, -1.33000078]])

### [5] 랜덤값 고정

랜덤이란 사전에 잘 섞여 있는 숫자 셋을 순차적으로 꺼내는 것을 의미한다. 

랜덤시드는 몇번째 숫자 셋인지를 의미하는 값

이 값을 고정하면 특정 숫자셋만 사용하라는 의미

In [25]:
np.random.seed(1234) # 임의의수
np.random.normal(0,1,(4,3))

array([[ 0.47143516, -1.19097569,  1.43270697],
       [-0.3126519 , -0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ,  0.01569637],
       [-2.24268495,  1.15003572,  0.99194602]])